// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmeffuyibncdrxtpjeau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZWZmdXlpYm5jZHJ4dHBqZWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjcwODQsImV4cCI6MjA2NjUwMzA4NH0.b_RaWLQDHH-WEae1Z8MOHhaet2oc-dMp3ly0-YP49AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);